name: Compile and Trigger Qodana Scan

on:
  push:
    branches: [Develop]
  pull_request:
    branches: [Develop]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: maven
          
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Compile code
        run: mvn clean install

      - name: Run tests
        run: mvn test

      - name: Create Pull Request to qodana-scan
        if: success()
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PAT }}
          branch: Qodana-scan
          title: 'Merge develop into qodana-scan'
          body: 'This PR is automatically created by GitHub Actions to merge develop into qodana-scan.'

      # - name: Trigger Qodana Scan
      #   uses: peter-evans/repository-dispatch@v3
      #   with:
      #     token: ${{ secrets.PAT }}
      #     event-type: trigger-qodana-scan

#  qodana:
#    needs: compile
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#      - name: Trigger Qodana Scan
#        uses: peter-evans/repository-dispatch@v3
#        with:
#          #          token: ${{ secrets.QODANA_TOKEN }}
#          event-type: trigger-qodana-scan
