name: Compile and Trigger Qodana Scan

on:
  push:
    branches: [ Develop ]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: maven

      - name: Compile code
        run: mvn clean install

      - name: Trigger Qodana Scan
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.QODANA_TOKEN }}
          event-type: trigger-qodana-scan

#  qodana:
#    needs: compile
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#      - name: Trigger Qodana Scan
#        uses: peter-evans/repository-dispatch@v3
#        with:
#          #          token: ${{ secrets.QODANA_TOKEN }}
#          event-type: trigger-qodana-scan
