name: Qodana Scan

on:
  repository_dispatch:
    types: [trigger-qodana-scan]

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v4
        with:
          pr-mode: false
          args: --apply-fixes
          push-fixes: pull-request
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Qodana scan
        uses: JetBrains/qodana-action@v2024.1.3
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN}}

      - name: Merge to Master
        if: success()
        uses: devmasx/merge-branch@v1.4.0
        with:
          type: now
          target_branch: master
          github_token: ${{ secrets.GITHUB_TOKEN }}
