name: Qodana Scan

on:
  push:
    branches: [Qodana-scan]
  pull_request:
    branches: [Qodana-scan]

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v4
        with:
          pr-mode: false
          args: --apply-fixes
          push-fixes: pull-request
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Qodana scan
        uses: JetBrains/qodana-action@v2024.1.3
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN}}
          
  master-merge:
    needs: qodana
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create Pull Request to master
        if: success()
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PAT }}
          branch: master
          title: 'Merge qodana-scan into master'
          body: 'This PR is automatically created by GitHub Actions to merge qodana-scan into master after successful code scan.'
